# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"
gem "pry", "~> 0.14.1"
gem "rubocop", "~> 1.19"
