---
title: Ziyyon is my home
substitute:
  - ['Zion', 'Ziyyon']
comments: commentary.html
layout: layout.html.erb # add this.
page: ziyyon.html.erb
verse_template: _verse_list.html.erb
verses: verses.yml
import: verses.txt
output: index.html
stylesheet: true
