---
title: There is power in my home
substitute:
  - ['power', 'power']
comments: commentary.html
layout: layout.html.erb # add this.
dir: power
search:  power
page: page.html.erb
verse_template: _verse_list.html.erb
verses: verses.yml
import: verses.txt
output: index.html
stylesheet: true