# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "httparty"
gem 'pry'
gem 'nokogiri'
gem 'rb-readline'
gem 'rspec'
gem 'awesome_print'

